language: python
python:
    - "2.7"

sudo: required
        
branches:
  only:
    - master

env:
    global:
        - USR_NAME="Sun Yuxi (IFAG DES SDF FW)"
        - USR_EMAIL="Yuxi.Sun@infineon.com"
        ####generate new token for each repo####
        - secure: IfRlWFhvPv7sdpNV9fOWyNBec6n/FsvTONc4SD+xyaDYUTCdCCsSNRu87vsoMmvb/stVJtOGfsqoOqb087pMCNJ7Lhes7qFobGOFwLy1gyYQtCTDYoKReWOtqreBqD+pdRs7ztozYJKOwnYCySet2wgH3s6ovwLhZd8TcydRjvUjQRRsSf0BcALTASEjhLzOU+TQj7Ak7exeSfzafhICeZCvYMhCekeNKfGdDd0P4B8VLEdvLGvXKfegLvm/+O1FGvohztcEANYzAAR98zQfRVXw0jY4zXA1mFEH8nLQTIYBrvSO/YSaTWJRcfJtVvOnShcb/T+mJqiKoVvsu/T5NadmATbqjSL/9xHdQJbLu8WRnCUeRQC40lrFSfCm76OtuGdpZkiPaVHGMft1QyABjuvWLaIe0XThfYBjlSEN8MMSlp08PbbV+dW7Oj3thm3yB+MYEvcVVc30vIp+zMd6GDHEhR6KiRLwJ+eU6tGWlbydIq/s9JmIi+oiRXVVfMK6Ylz5gqq2pw3rODoey3/I+7veW6YY2MrgAYq1KaEeXqpBJLfb9D5GTVI5pgk2aRFunuPdxX9UuT1SfOs1RfEo3MXk5uyP38aENvYCoFHZ6hxi60NA+kFINTn6ej0RdaUe0418og0XwDIwztiFIW9Sj2kKpi943L+mAAksImm+tqs=
    matrix:
        ##########change example paths##########
        - PLATFORMIO_CI_SRC=examples/pong 
        - PLATFORMIO_CI_SRC=examples/print_raw_data 
        
install:
    # build with stable core
    - pip install -U platformio
    - platformio platform install -f infineonxmc
script:
    - platformio ci --lib="." --board=xmc1100_xmc2go --board=xmc1100_boot_kit --board=xmc1100_h_bridge2go --board=xmc1300_boot_kit --board=xmc4700_relax_kit
 
after_success:
    # only build once (after one job by checking id, however this does not work reliably)
    - |
      if [ $(($TRAVIS_JOB_ID - $TRAVIS_BUILD_ID)) -eq 2 ]; then
        export REPO_NAME=${TRAVIS_REPO_SLUG#*/}
        git clone https://github.com/Infineon/well-automated-documentation.git
        cd well-automated-documentation/docs
        # cd $TRAVIS_BUILD_DIR/docs
        chmod +x publish_pdf.sh
        ./publish_pdf.sh
      fi